Cargo.lock, contracts/script/output/42070/coprocessor_deployment_output.json, contracts/script/output/42070/matching_game_deployment_output.json, contracts/script/output/42070/mock_consumer_deployment_output.json, crates/scripts/Cargo.toml, crates/scripts/src/node_test.rs
- Deploys `MatchingGameConsumer` contract to devnet
- Adds logic in `node_test.rs` to test submitting a job with offchain input to the remote coprocessor node and verify that the result is successfully posted onto the L1 devnet. This implicitly tests the blob submission flow, since the job result will only be accepted by the `JobManager` if the blob hashes are correct. We use the `MatchingGameConsumer` as an example of a consumer which has a job with offchain input.
`cargo run --bin node-test`: Passes
=> test: Add script to test submitting job with offchain input to remote node

.github/workflows/docker-coproc.yml, Dockerfile.coprocessor-node
We broke the docker build when we renamed the coprocessor node crate to `ivm-coprocessor-node`. While fixing this I also realized we don't need the risc0 base image since we don't build any risc0 binaries, just the coprocessor-node binary. We also no longer rely on building the contracts at build time, the abi is committed in the crate.
Changes
- Don't install or use foundry
- Don't use a risc0 base image
- Add some apt installs
=> fix: coprocessor-node dockerfile

Cargo.lock, Cargo.toml, crates/coprocessor-node/Cargo.toml, crates/coprocessor-node/src/cli.rs, crates/coprocessor-node/src/intake.rs, crates/coprocessor-node/src/job_processor.rs, crates/coprocessor-node/src/node.rs, crates/zkvm-executor/Cargo.toml
- We use the `zkvm-executor` crate in the foundry template now, so we rename it to `ivm-zkvm-executor`
=> refactor: Rename `zkvm-executor` to `ivm-zkvm-executor`

book/src/apps/clob.md, book/src/apps/matching-game.md, book/src/apps/square-root.md, book/src/coprocessor/api.md, book/src/integration/offchain.md, book/src/integration/onchain.md, book/src/integration/writing-program.md
- Updates some of the info in the book to sp1 (repo structure, zkVM program code, etc.)
- Removes line numbers in any github URLs in the book because these line numbers keep changing and we don't want to confuse readers by directing them to wrong line numbers
=> doc: Update book to sp1 and remove line numbers

examples/clob/programs/build.rs, examples/matching-game/programs/build.rs, programs/intensity-test/build.rs, programs/mock-consumer/build.rs
- Add `cargo rerun` to the `build.rs` scripts for ELFs so we don't need to rebuild the ELFs every time we run `cargo build`
Ran `cargo build` a few times and verified that we don't rebuild the ELFs
=> fix: add cargo rerun for ELF builds

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, examples/clob/programs/program/Cargo.lock, examples/clob/programs/program/Cargo.toml, examples/matching-game/programs/program/Cargo.lock, examples/matching-game/programs/program/Cargo.toml, programs/intensity-test/program/Cargo.lock, programs/intensity-test/program/Cargo.toml, programs/mock-consumer/program/Cargo.lock, programs/mock-consumer/program/Cargo.toml, test/e2e/tests/clob.rs, test/e2e/tests/matching_game.rs, test/e2e/tests/mock_consumer.rs
Changes
- Guest program had build deps event tho they didn't have build logic. We remove these
- Reduce timeouts in e2e tests and force tokio test worker threads in some places to reduce chances of slow tasks blocking. Since we refactored the CN to use standard OS threads, job execution should be faster and we should be able to reduce tiemouts
=> chore: remove unused sp1 build deps

Cargo.lock, crates/scripts/src/local.rs, crates/scripts/src/node_test.rs, crates/sdk/sp1-utils/src/lib.rs, crates/zkvm/src/lib.rs, examples/clob/node/src/batcher.rs, examples/clob/programs/Cargo.toml, examples/clob/programs/src/lib.rs, examples/matching-game/programs/Cargo.toml, examples/matching-game/programs/src/lib.rs, examples/matching-game/server/src/batcher.rs, programs/intensity-test/Cargo.toml, programs/intensity-test/src/lib.rs, programs/mock-consumer/Cargo.toml, programs/mock-consumer/src/lib.rs, test/e2e/tests/clob.rs, test/e2e/tests/matching_game.rs, test/e2e/tests/mock_consumer.rs, test/load-test/src/main.rs
- Uses the program ID path instead of lazy init
`make test-all`: Passes
=> refactor: use program ID path instead of lazy

CONTRIBUTING.md, Makefile, crates/coprocessor-node/Cargo.toml
`cargo run --bin local` was not working because of some missing Alloy features.
- Adds these features
`make run`: Works correctly
=> fix: Add alloy features to get local script working

.github/workflows/docker-exec.yml
Fixes the docker build and push for ivm reth which was erroneously pushing to the coproc docker repo
=> coproc -> ivm-reth

crates/coproc/src/relayer.rs
- The relayer test was flaky because we were sometimes attempting to submit result for job with nonce 0 after nonce 1
- Fixes this by relaying all results sequentially in the test
`make test-all`: Passes
=> fix: Relay results sequentially to prevent flakiness in relayer test

Cargo.lock, Cargo.toml, examples/clob/programs/program/Cargo.lock, examples/matching-game/programs/program/Cargo.lock
Update reth and alloy deps. There seems to be some implicit feature gating updates that will help ivm lib consumers build ivm deps and reth deps in the same workspace
=> chore(deps): update reth & alloy

book/src/coprocessor/run.md
Fixes a broken link to the coprocessor dockerfile  in the generated mdbook.
=> fix: fixes broken link to Dockerfile

.dockerignore, Dockerfile.exec, entrypoint-exec.sh
As a part of https://github.com/InfinityVM/infra/issues/74
Exposes port `9100`
Adds an entrypoint.sh script to run `node_exporter` as a background service, as well as `reth` - the main service, on startup
=> feat: starts node_exporter as well as reth on startup

Dockerfile.coprocessor-node, Dockerfile.exec
Exposes port `9100` on the coprocessor docker container
=> fix: exposes port 9100 and cleaner --copy

bin/exec/src/main.rs
Targets #444
This PR updates us to use the new engine. Not only is the new engine faster and easier to understand, it also unlocks dev/auto mine mode for us.
This now works!
```rust
cargo run -p ivm-exec -- node --dev --dev.block-time 1s
```
=> refactor: use new reth engine

Cargo.lock, Cargo.toml, bin/exec/Cargo.toml, bin/exec/src/config.rs, bin/exec/src/engine.rs, bin/exec/src/evm/builder.rs, bin/exec/src/evm/mod.rs, bin/exec/src/lib.rs, bin/exec/src/main.rs, bin/exec/src/pool/mod.rs, bin/exec/src/pool/validator.rs
Targets #443 
Changes:
- Don't use reth or alloy facade crates in ivm-exec
- Adds in the jemalloc setup from reth utils. I was noticing reth uses this, so I figured we might as well. But I can remove if not desirable.
=> chore(deps): don't use facade crates in `ivm-exec`

.github/actions/setup/action.yml, bin/exec/src/pool/validator.rs, crates/coproc/src/cli.rs, crates/coproc/src/event.rs, crates/coproc/src/execute.rs, examples/clob/node/src/batcher.rs, examples/clob/node/src/event.rs, rust-toolchain.toml
I kept getting diffs when running `cargo fmt` vs `cargo +nightly fmt`. The way I generated this diff was by running `cargo fmt`, pinning the toolchain, and then re-running `cargo fmt`.
=> chore(toolchain): use nightly-2025-01-11; run fmt

Cargo.lock, Cargo.toml, crates/zkvm-executor/Cargo.toml, crates/zkvm-executor/src/service.rs
Closes #475 
This is a breaking change for any one consuming coproc blob data
I chose lz4 because, from what I understood, the compressed data will likely be smaller then snappy
=> feat(coproc): compress offchain input before blob enconding

Cargo.lock, crates/coproc/Cargo.toml, crates/coproc/src/intake.rs
Follow up to #476. We want to validate compressed data length, else risk rejecting offchain input that would be valid once compressed.
=> fix(coproc): validate compressed data length

.dockerignore, Dockerfile.coproc, Dockerfile.exec, entrypoint-exec.sh
We had included node_exporter into to running container when we were running via terraform. Now that this is deployed into K8s we are getting these metrics from kubelet directly for all of our pods.
We don't need node_exporter to be directly included anymore.
=> Removes node_exporter and entrypoint.sh

bin/exec/src/config/mod.rs
Essentially the same as #499, but just using the timestamp based forking so we can sanity check it works in prod.
=> chore(ivm-exec): add fork for 2025.2.5

contracts/src/clob/ClobConsumer.sol, contracts/src/coprocessor/Consumer.sol, contracts/src/coprocessor/OffchainRequester.sol, contracts/src/coprocessor/SingleOffchainSigner.sol, contracts/src/coprocessor/StatefulConsumer.sol
- Adds storage gaps in the base coproc contracts like `SingleOffchainSigner` and `StatefulConsumer`
=> fix: Add storage gaps in base coproc contracts

contracts/src/clob/ClobConsumer.sol, contracts/src/coprocessor/OffchainRequester.sol, contracts/src/coprocessor/SingleOffchainSigner.sol, contracts/src/coprocessor/StatefulConsumer.sol
- Removes storage gap from contracts other than the abstract contract `Consumer.sol`
`forge test`: Passes
=> fix: Only storage gap in abstract contract

crates/coproc/src/intake.rs, crates/coproc/src/server.rs, crates/db/src/tables.rs
Prior to this job, if there is an error with a job a consumer has no way to overwrite that nonce. This updates the logic to always overwrite an old with a newer job with the same nonce, if they are not equal
=> feat: allow overwriting job

bin/exec/src/config/mod.rs
Changes:
- Remove senders from allowed `to` field
- Add new contracts to allowed `to` field
=> chore: add deployed contracts to suzuka

crates/coproc/src/metrics.rs
The new histogram for job execution times goes up to 3 minutes now.
=> fix: Increase histogram range of job execution times
